cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

project(@THIRD_PARTY_NAME@-fetch NONE)

include(ExternalProject)

ExternalProject_Add(@THIRD_PARTY_NAME@
  GIT_REPOSITORY  https://github.com/google/leveldb.git
  GIT_TAG         1.23

  SOURCE_DIR    @THIRD_PARTY_DOWNLOAD_SRC_DIR@
  BINARY_DIR    @THIRD_PARTY_DOWNLOAD_BUILD_DIR@

  INSTALL_INCLUDE_DIR @THIRD_PARTY_DOWNLOAD_INSTALL_DIR@/include
  INSTALL_LIB_DIR @THIRD_PARTY_DOWNLOAD_INSTALL_DIR@/lib

  CMAKE_ARGS 
    -DCMAKE_INSTALL_PREFIX=@THIRD_PARTY_DOWNLOAD_INSTALL_DIR@
    -DLEVELDB_BUILD_TESTS=OFF
    -DLEVELDB_BUILD_BENCHMARKS=OFF
)
